name: stagexl_samples
author: Bernhard Pichler
description: Sample applications showing features of the StageXL library.
homepage: http://www.stagexl.org/
dependencies:
  browser: any
  stagexl: any
  stagexl_flump: any
  stagexl_richtextfield: any
