name: stagexl_samples
author: Bernhard Pichler
homepage: http://www.stagexl.org/
description: Sample applications showing features of the StageXL library.
dependencies:
  browser: any
  stagexl: '>=0.9.0 <0.10.0'
  stagexl_flump: any
  stagexl_richtextfield: '>=0.1.1 <0.2.0'
